### ISSUE TITLE
Fetch and show real time data on same page...

### ISSUE THREAD

**Issue by tejasklodha** [titanium-as/TitaniumAS.Opc.Client#11]
Dear sir,

I made wpf application which fetch opcda data using your library and i am able to show real-time data on screen for one opc server.....

Now I want to show multiple opc server data on same screen....

How can i achieve this on same page??

Thanks,

**Comment by alexey-kachalov** [comment]
Hi. I think you can use several instances of OpcDaServer for that.

**Comment by tejasklodha** [comment]
Dear sir,

Can you give me demo for 3 instance use efficiently...?

**Comment by alexey-kachalov** [comment]
Hi again. I have a couple of news for you:

1. We have a good solution for such tasks. It supports an interaction with a collection of OPC DA servers, also with multithreaded bindings for WPF. It can work with OPC DA servers which don't support values changed event with the same manner as for those which support that. Also you can easily configure you runtime. And many other things.

2.  But the solution isn't free software. If you interest with it, don't bother to contact me with a private conversation.
