### ISSUE TITLE
Bootstrap Throwing Error about CoInitializeSecurity

### ISSUE THREAD

**Issue by sarthak-k** [titanium-as/TitaniumAS.Opc.Client#17]
Hi,

I'm currently facing some issue with the initialization of the DA Client. The external exception throws: CoInitializeSecurity: Security must be initialized before any interfaces are marshalled or unmarshalled. It cannot be changed once initialized.

Can anybody point me how to start console application with this library?

**Comment by alexey-titov** [comment]
From readme.md: https://github.com/titanium-as/TitaniumAS.Opc.Client:

Bootstrapping the library

Call Bootstrap.Initialize() in the start of your application. An application process should be started **under MTA apartment** state due to CoInitializeSecurity call during the library initialization.
