### ISSUE TITLE
Getting a list of available OPC servers

### ISSUE THREAD

**Issue by terndrup** [titanium-as/TitaniumAS.Opc.Client#18]
Hey there,

great library! I've just been messing around with it today and it's working mostly great but I have one question.

Is there a way to get all available Opc servers on the machine? I know other Opc DA client libraries can do this and it's important if you don't know the name of the server.

Thanks and keep up the good work!

**Comment by terndrup** [comment]
This is related to #9

If you can point me to some information about how OpcServer browsing works I could try implementing it. But I'm new to OPC Clients so I'm a bit lost

**Comment by alexey-titov** [comment]
Hello! Thanks for review.

You can enumerate hosts and servers with OpcServerEnumeratorAuto.

See tests for details. TitaniumAS.Opc.Client/TitaniumAS.Opc.Client.Tests/Common/OpcServerEnumeratorAutoTests.cs
