### ISSUE TITLE
List all OPC Server register in computer (OPC_Enum)

### ISSUE THREAD

**Issue by microgenios** [titanium-as/TitaniumAS.Opc.Client#26]
Hello 
Is possible list all OPC Server installed in PC with TitaniumAS?
Best Regards
Fernando

**Comment by alexey-kachalov** [comment]
Hi! Yes it is. Try to use `OpcServerEnumeratorAuto` like it is here https://github.com/titanium-as/TitaniumAS.Opc.Client/blob/master/TitaniumAS.Opc.Client.Tests/Common/OpcServerEnumeratorAutoTests.cs#L45

Sorry for the lack of docs.

**Comment by microgenios** [comment]
Very, very good job! 
Thanks Alexey
Fernando
